steps = 100000
print_every = 1000
print_trajectory_every = 10000
N = 64
dt = 0.001
initial_density = 0.01
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_jax = true

[landau]
epsilon = 0.9