steps = 2000000
print_every = 100000
print_trajectory_every = 100000
N = 64
dt = 0.001
dx = 1
dim = 2
interface_scalar = 1.0
free_energy = "custom"
integrator = "euler"
model = 'CH'
use_autodiff = false
L_phi = 1.0
custom_initial_condition = true

[PINN_test]
delta = 1.0