steps = 150000
print_every = 1000
print_trajectory_every = 5000
N = 64
dt = 0.0001
initial_density = 0.01
free_energy = "magnetic_film"
integrator = "euler"
model = 'AC'
use_autodiff = false  # Source of stability here!
ch_diff_method = 'central'
interface_scalar = 1.0
gamma = 0.9

[magnetic_film]
delta = 4.0