steps = 3e4
print_every = 1e3
print_trajectory_every = 1e3
N = 64
dt = 1e-6
initial_density = 9e-5
free_energy = "saleh"
dx = 10
k = 1e6
use_autodiff = false

[saleh]
valence = [4, 4, 4]
B2 = 2190

[saleh.delta_AA]
T = 293.15
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6

[saleh.delta_BB]
T = 293.15
deltaH = -42400
deltaS = -120.6
salt = 0.5
sticky_size = 6