steps = 10000000
print_every = 25000
print_trajectory_every = 200000
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = false
diff_method = 'central'
interface_scalar = 2.0
write_path = './jax_results/'
initial_density = 0.01

[landau]
epsilon = 0.9