steps = 10000000
print_every = 1e5
print_trajectory_every = 1e5
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = false
interface_scalar = 2.0
initial_density = 0.01
float_type = "float64"  # MUST BE FLOAT64 (float32 fails with explicit euler!)
write_path = "/mnt/nvme/home/avetturi/phase-field-models/Examples/Landau/euler_noautodiff"
load_from = "/mnt/nvme/home/avetturi/phase-field-models/Examples/Landau/standard_input.dat"

[landau]
epsilon = 0.9