steps = 10000000
print_every = 1e5
print_trajectory_every = 1e5
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = false
interface_scalar = 2.0
initial_density = 0.01
float_type = "float64"
write_path = "test1"
load_from = "standard_input.dat"

[landau]
epsilon = 0.9