steps = 1000000
print_every = 25000
print_trajectory_every = 25000
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = true
interface_scalar = 2.0
initial_density = 0.01
float_type = "float32"

[landau]
epsilon = 0.9