steps = 10000000
print_every = 1e5
print_trajectory_every = 1e5
N = 64
dt = 0.001
free_energy = "landau"
integrator = "spectral"
model = 'CH'
use_autodiff = true
interface_scalar = 2.0
initial_density = 0.01
float_type = "float64"
write_path = "Landau/spectral_autodiff"
load_from = "Landau/standard_input.dat"

[landau]
epsilon = 0.9