steps = 10000000
print_every = 1000
print_trajectory_every = 200000
N = 64
dt = 0.001
free_energy = "landau"
use_CUDA = true
initial_density = 0.01
#load_from = '/home/aj/GitHub/phase-field-models/Examples/Landau/cuda_vs_jax/init_0.dat'

[landau]
epsilon = 0.9


