#steps = 1000000
steps = 100
print_every = 10
print_trajectory_every = 10
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = true
interface_scalar = 2.0
initial_density = 0.01
float_type = "float32"
verbose = false

[landau]
epsilon = 0.9