steps = 100000
print_every = 10000
print_trajectory_every = 200000
N = 64
dt = 0.001
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = false
ch_diff_method = 'central'
interface_scalar = 2.0
write_path = './jax_results/'
load_from = 'init_0.dat'

[landau]
epsilon = 0.9