steps = 10000000
print_every = 1e5
print_trajectory_every = 1e5
N = 64
dt = 0.001
initial_density = 0.01
free_energy = "landau"
use_CUDA=true
load_from = "/mnt/nvme/home/avetturi/phase-field-models/Examples/Landau/standard_input.dat"

[landau]
epsilon = 0.9
