steps = 10000
print_every = 10000
print_trajectory_every = 200000
N = 64
dt = 0.001
initial_density = 0.01
free_energy = "landau"
integrator = "euler"
model = 'CH'
use_autodiff = false  # Source of stability here!
ch_diff_method = 'central'
interface_scalar = 2.0

[landau]
epsilon = 0.9