steps = 500000
print_every = 10000
print_trajectory_every = 250000
N = 64
dt = 0.001
initial_density = 0.01
free_energy = "landau"
integrator = "euler"
model = 'AC'
use_autodiff = true  # Source of stability here!
ch_diff_method = 'central'

[landau]
epsilon = 0.9