steps = 1e8
print_every = 1e5
print_trajectory_every = 1e7
N = 512
dt = 1e-5
initial_density = 5e-5
free_energy = "simple_wertheim"
dx = 10
k = 1e6
write_path = './jax/'

[wertheim]
valence = 4
B2 = 2190

[wertheim.delta]
T = 303.15
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6