steps = 1e8
print_every = 1e6
print_trajectory_every = 1e6
N = 512
dt = 1e-6
initial_density = 2e-5
free_energy = "saleh"
dx = 10
k = 1e6
use_autodiff = true
interface_scalar = 2.0
float_type = "float64"
write_path = "Wertheim/saleh_wertheim/euler_autodiff"

[saleh]
valence = [4, 4, 4]
B2 = 2190

[saleh.delta_AA]
T = 300.00
deltaH = -42200
deltaS = -119.1
salt = 0.5
sticky_size = 6

[saleh.delta_BB]
T = 300.00
deltaH = -42400
deltaS = -120.6
salt = 0.5
sticky_size = 6