steps = 500
print_every = 10
print_trajectory_every = 2
N = 100
dt = 0.01
dx = 1
dim = 1
free_energy = "custom"
integrator = "euler"
model = 'AC'
use_autodiff = false
L_phi = 1.0
custom_initial_condition = true

[magnetic_film]
delta = 1.0